apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicegateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicegateway
  template:
    metadata:
      labels:
        app: servicegateway
    spec:
      containers:
      - name: servicegateway
        image: sakthisaransss55/servicegateway:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: servicegatewayservice
spec:
  type: LoadBalancer
  selector:
    app: servicegateway
  ports:
  - port: 80
    targetPort: 80

